#!/usr/bin/env python3
# Downloads all landmark images from Wikimedia and rewrites landmarks.js
# to use local paths served from /data/landmark-photos/.
# Usage: python3 scripts/download-landmark-photos.py

import json, re, os, time, urllib.request, urllib.parse

LANDMARKS_JS = os.path.join(os.path.dirname(__file__), '../backend/public/data/landmarks.js')
OUT_DIR = os.path.join(os.path.dirname(__file__), '../backend/public/data/landmark-photos')

os.makedirs(OUT_DIR, exist_ok=True)

with open(LANDMARKS_JS, encoding='utf-8') as f:
    content = f.read()

data = json.loads(re.search(r'const LANDMARKS = (\[.*\]);', content, re.DOTALL).group(1))

results = []
failed = []

for entry in data:
    # Build a safe filename from the landmark name
    slug = re.sub(r'[^a-z0-9]+', '-', entry['name'].lower()).strip('-')
    filename = f"{slug}.jpg"
    local_path = os.path.join(OUT_DIR, filename)
    local_url = f"/data/landmark-photos/{filename}"

    print(f"Downloading: {entry['name']} ... ", end='', flush=True)
    try:
        req = urllib.request.Request(entry['photo_url'], headers={
            'User-Agent': 'GeoStreak/1.0 (https://github.com/BasEijs/geostreak)'
        })
        with urllib.request.urlopen(req, timeout=15) as r:
            img_bytes = r.read()
        with open(local_path, 'wb') as f:
            f.write(img_bytes)
        kb = len(img_bytes) // 1024
        print(f"OK ({kb}KB)")
        results.append({"name": entry["name"], "iso": entry["iso"], "photo_url": local_url})
    except Exception as e:
        print(f"FAILED — {e}")
        failed.append(entry)
    time.sleep(0.15)

# Rewrite landmarks.js with local URLs
js_content = (
    "// Auto-generated by scripts/download-landmark-photos.py — do not edit by hand\n"
    "// To add landmarks: edit the SEED in fetch-landmark-photos.py, re-run it,\n"
    "// then run download-landmark-photos.py to download the new images.\n\n"
    f"const LANDMARKS = {json.dumps(results, indent=2, ensure_ascii=False)};\n"
)

with open(LANDMARKS_JS, 'w', encoding='utf-8') as f:
    f.write(js_content)

print(f"\nWrote {len(results)} landmarks to landmarks.js with local paths")
print(f"Images saved to {os.path.abspath(OUT_DIR)}")

if failed:
    print(f"\nFailed ({len(failed)}) — these kept their Wikimedia URLs:")
    for e in failed:
        print(f'  {e["name"]}')
